### ISSUE TITLE
Receive "Error: Cannot find module './models'" when running "yarn start" from the project root directory.

### ISSUE THREAD

**Issue by philipstubbs13** [philipstubbs13/MedLog#33]
When I run "yarn start" from the project root directory, I get the following error in the terminal:

[0] module.js:540
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module './models'
[0]     at Function.Module._resolveFilename (module.js:538:15)
[0]     at Function.Module._load (module.js:468:25)
[0]     at Module.require (module.js:587:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\phili\Desktop\dev_bootcamp\projects\MedLog\server.js:10:12)
[0]     at Module._compile (module.js:643:30)
[0]     at Object.Module._extensions..js (module.js:654:10)
[0]     at Module.load (module.js:556:32)
[0]     at tryModuleLoad (module.js:499:12)
[0]     at Function.Module._load (module.js:491:3)
[0]     at Function.Module.runMain (module.js:684:10)
[0]     at startup (bootstrap_node.js:187:16)
[0]     at bootstrap_node.js:608:3

**Comment by philipstubbs13** [comment]
Issue resolved. Added index.js file to the models directory:

module.exports = {
  User: require('./User'),
  Clinic: require('./Clinic'),
  Doctor: require('./Doctor'),
  Healthlog: require('./Healthlog'),
  Appointment: require('./Appointment'),
};

Error occured because the index.js file was missing from the models folder. This file exports the models so that the server can see them.
